"""Generates `docs/DECISION_MATRIX.md` — every case in `MATRIX`, `EXPORT_MATRIX`
and `API_KEY_MATRIX` (packages/authz-core/tests/test_policy_matrix.py), evaluated
through a real `PolicyEngine`. A reviewer reads the whole permission model on one
page instead of trusting a paragraph.

The committed file is this script's stdout, verbatim. `tests/test_matrix_doc_is_current.py`
re-runs it and diffs — a generated doc that can drift from its source is worse
than no doc.

Run:
    uv run python scripts/generate_matrix.py > docs/DECISION_MATRIX.md
"""

import sys
from pathlib import Path

# Same trick as src/app/cli.py: import the authz-core test fixtures directly
# rather than duplicating MATRIX/build_slice, so the generated table and the
# test expectations it was generated from cannot drift apart.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "packages" / "authz-core"))

from authz_core import Action, AuthzContext, EngineError, PolicyEngine
from tests.test_policy_matrix import API_KEY_MATRIX, EXPORT_MATRIX, MATRIX, TEAM, WF

from tests.conftest import build_slice

Row = tuple[str, str, str, str, str]


def _decide(engine: PolicyEngine, **kwargs: object) -> tuple[str, str]:
    decision = engine.authorize(**kwargs)  # type: ignore[arg-type]
    if isinstance(decision, EngineError):
        return "ERROR", decision.message
    return ("ALLOW" if decision.allowed else "DENY"), (decision.policy_id or "—")


def _rows(engine: PolicyEngine) -> list[Row]:
    rows: list[Row] = []

    for role, action, resource, _expected in MATRIX:
        principal, slice_ = build_slice(role)
        decision, policy = _decide(
            engine,
            principal=principal,
            action=action,
            resource=resource,
            slice_=slice_,
            context=AuthzContext(auth_method="jwt"),
        )
        rows.append((role, action.value, resource.type, decision, policy))

    for exported, visibility, protected, verified, in_org, _expected, why in EXPORT_MATRIX:
        principal, slice_ = build_slice(
            "anonymous",
            exported=exported,
            visibility=visibility,
            password_protected=protected,
            in_org=in_org,
        )
        state = (
            f"exported={exported}, visibility={visibility}, "
            f"pw_protected={protected}, pw_verified={verified}, in_org={in_org}"
        )
        decision, policy = _decide(
            engine,
            principal=principal,
            action=Action.WORKFLOW_RUN_EXPORTED,
            resource=WF,
            slice_=slice_,
            context=AuthzContext(auth_method="anonymous", password_verified=verified),
        )
        rows.append(
            (f"anonymous ({why})", Action.WORKFLOW_RUN_EXPORTED.value, state, decision, policy)
        )

    for action, scopes, _expected, why in API_KEY_MATRIX:
        resource = TEAM if action in {Action.TEAM_DELETE, Action.TEAM_ADD_MEMBER} else WF
        principal, slice_ = build_slice("super_admin")
        decision, policy = _decide(
            engine,
            principal=principal,
            action=action,
            resource=resource,
            slice_=slice_,
            context=AuthzContext(
                auth_method="api_key", api_key_scopes=scopes, api_key_org_id="org-1"
            ),
        )
        rows.append(
            (
                f"super_admin, api key ({why})",
                action.value,
                f"scopes={sorted(scopes)}",
                decision,
                policy,
            )
        )

    return rows


def main() -> None:
    rows = _rows(PolicyEngine())

    print("# Decision matrix")
    print()
    print(
        "Generated by `scripts/generate_matrix.py` from the policy-matrix tests "
        "(`packages/authz-core/tests/test_policy_matrix.py`), evaluated through a "
        "real `PolicyEngine`. Do not hand-edit — regenerate with:"
    )
    print()
    print("```")
    print("uv run python scripts/generate_matrix.py > docs/DECISION_MATRIX.md")
    print("```")
    print()
    print("| Role / context | Action | Resource state | Decision | Deciding policy |")
    print("|---|---|---|---|---|")
    for role, action, state, decision, policy in rows:
        print(f"| {role} | {action} | {state} | {decision} | {policy} |")


if __name__ == "__main__":
    main()
